#!/usr/bin/env node
// Codegen: packages/protocol/schema/protocol.json -> TS + Go (design.md §8, §11).
// Zero dependencies (Node built-ins only). Outputs are gitignored — regenerate,
// don't hand-edit. TODO: emit Zod schemas alongside the TS interfaces.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const schemaPath = resolve(root, "packages/protocol/schema/protocol.json");
const tsOut = resolve(root, "packages/protocol/src/index.ts");
const goOut = resolve(root, "services/pkg/protocol/protocol.go");

const TS = { string: "string", int: "number", bool: "boolean" };
const GO = { string: "string", int: "int64", bool: "bool" };

// Compound types: "T[]" arrays and "map<K,V>" maps; both nest. Anything else is
// a scalar (mapped via the tables above) or a named type (passed through).
const mapParts = (t) => {
  const inner = t.slice(4, -1);
  const i = inner.indexOf(",");
  return [inner.slice(0, i).trim(), inner.slice(i + 1).trim()];
};
const tsType = (t) => {
  if (t.endsWith("[]")) return `${tsType(t.slice(0, -2))}[]`;
  if (t.startsWith("map<") && t.endsWith(">")) {
    const [k, v] = mapParts(t);
    return `Record<${tsType(k)}, ${tsType(v)}>`;
  }
  return TS[t] ?? t;
};
const goType = (t) => {
  if (t.endsWith("[]")) return `[]${goType(t.slice(0, -2))}`;
  if (t.startsWith("map<") && t.endsWith(">")) {
    const [k, v] = mapParts(t);
    return `map[${goType(k)}]${goType(v)}`;
  }
  return GO[t] ?? t;
};
const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);

const banner = (src) =>
  `// Code generated by tools/protogen. DO NOT EDIT.\n// Source: ${src}\n`;

function genTS(schema) {
  const lines = [banner("packages/protocol/schema/protocol.json"), ""];
  for (const [name, fields] of Object.entries(schema.types)) {
    lines.push(`export interface ${name} {`);
    for (const [k, t] of Object.entries(fields)) lines.push(`  ${k}: ${tsType(t)};`);
    lines.push("}", "");
  }
  lines.push("export const RpcMethod = {");
  for (const m of schema.methods) lines.push(`  ${m.name}: ${JSON.stringify(m.name)},`);
  lines.push("} as const;", "");
  lines.push("export type RpcMethod = (typeof RpcMethod)[keyof typeof RpcMethod];", "");
  return lines.join("\n");
}

function genGo(schema) {
  const lines = [banner("packages/protocol/schema/protocol.json"), "package protocol", ""];
  for (const [name, fields] of Object.entries(schema.types)) {
    lines.push(`type ${name} struct {`);
    for (const [k, t] of Object.entries(fields)) {
      lines.push(`\t${pascal(k)} ${goType(t)} \`json:"${k}"\``);
    }
    lines.push("}", "");
  }
  lines.push("// RPC method names.", "const (");
  for (const m of schema.methods) lines.push(`\tMethod${pascal(m.name)} = ${JSON.stringify(m.name)}`);
  lines.push(")", "");
  return lines.join("\n");
}

const schema = JSON.parse(await readFile(schemaPath, "utf8"));
await mkdir(dirname(tsOut), { recursive: true });
await mkdir(dirname(goOut), { recursive: true });
await writeFile(tsOut, genTS(schema));
await writeFile(goOut, genGo(schema));
console.log(`protogen: wrote\n  ${tsOut}\n  ${goOut}`);
